### ISSUE TITLE
Where is the integral computed in the code?

### ISSUE THREAD

**Issue by DeepRunner** [itaigat/removing-bias-in-multi-modal-classifiers#4]
Thank you for your interesting work. But I did not figure out what the code corresponds to the integral in the final loss (i.e. Eq. 19). It seems there is no code of sampling+sum(usually used to compute integral)  when computing the loss. Thank you!

**Comment by itaigat** [comment]
Eq. 19 is the variance variant of our method, and it is not implemented in this repository. In the paper, we focus on the functional entropy and functional Fisher information (Eq. 12) which you can find in the 'Regularization' class. 
You can easily modify the functional Fisher information code to just the gradient norm and achieve Eq. 19.
